#!/usr/bin/env python3
"""stage_video_research.py — stage dispatch-ready briefs for the NEW playlist videos.

⚠ RUN `video_backlog_diff.py` FIRST TO PRODUCE THE INPUT LIST. Do NOT hand-roll the "is this already
researched?" check. A naive grep of the hub for video URLs undercounts already-carded videos (legacy cards
store other source forms) — this fleet once re-staged a carded video that way and silently overwrote its
card. Correct flow:

    python3 video_backlog_diff.py --out /path/new.txt
    VIDEO_NEWVIDS=/path/new.txt python3 stage_video_research.py

Writes: a shared _DISPATCH_PREAMBLE.md (the video-research method), one brief
per video (specifics + transcript path), and STAGING_QUEUE.md (tiered dispatch list).
Transcripts: parses the fetched VTTs in _staging_transcripts/ -> clean transcript_<slug>_<id>.txt."""
import re, glob, os, sys

BASE = os.path.expanduser(os.environ.get("VIDEO_ROOT", "./video-research"))  # EDIT ME or set VIDEO_ROOT
VTT_DIR = f"{BASE}/_staging_transcripts"
OUT = f"{BASE}/_staged_briefs"
PREAMBLE_TEMPLATE = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "templates", "video-research", "_DISPATCH_PREAMBLE.md.template")
# input list ("<id>|<title>" per line). Was hard-coded to /tmp — shared by every parallel agent/job on the
# box, so two concurrent stagings clobber each other. Env-overridable now. (fix 2026-07-30)
NEWVIDS = os.environ.get("VIDEO_NEWVIDS", "/tmp/new_videos.txt")
os.makedirs(OUT, exist_ok=True)

# Owner's priority pin for THIS batch — was hard-coded to an old batch's id and silently
# misdirected dispatch on every later run. Now env-overridable and defaulted to the current batch's pin;
# set VIDEO_PRIORITY_PIN="" to disable. (fix 2026-07-30)
PRIORITY_PIN = os.environ.get("VIDEO_PRIORITY_PIN", "")  # EDIT ME: pin one of YOUR video ids, or leave unset

# Keep the generated brief's required relevance vocabulary visible to the four-surface agreement guard.
PROJECTS = ["Local-Models", "Flagship-App", "Fleet-Ops", "Tooling-Infra", "Research-Pipeline", "Memory"]

# fleet-relevance pre-screen (orchestrator judgment from titles)
HIGH = {
        # EDIT ME — example ids only; put YOUR high-priority video ids here
        "dQw4w9WgXcQ",
    }
LOW = {
        # EDIT ME — example ids only
        "oHg5SJYRHA0",
    }
def tier(v): return "HIGH" if v in HIGH else ("LOW" if v in LOW else "MED")

def parse_vtt(path):
    txt = open(path, encoding="utf-8", errors="replace").read()
    out, last = [], ""
    for ln in txt.splitlines():
        ln = ln.strip()
        if not ln or ln == "WEBVTT" or "-->" in ln or ln.startswith(("Kind:", "Language:", "NOTE", "STYLE", "::")):
            continue
        ln = re.sub(r"<[^>]+>", "", ln); ln = ln.replace("&nbsp;", " ").strip()
        if not ln or ln == last:
            continue
        if out and (ln in out[-1] or out[-1] in ln):     # rolling-caption overlap
            if len(ln) > len(out[-1]): out[-1] = ln
            last = ln; continue
        out.append(ln); last = ln
    return "\n".join(out)

def slug(t): return re.sub(r"[^a-z0-9]+", "-", t.lower()).strip("-")[:45]

# 1) shared preamble (the committed, portable research method)
try:
    with open(PREAMBLE_TEMPLATE, encoding="utf-8") as template_file:
        preamble = template_file.read()
except OSError:
    print(f"error: missing dispatch preamble template: {PREAMBLE_TEMPLATE}")
    sys.exit(1)
open(f"{OUT}/_DISPATCH_PREAMBLE.md", "w", encoding="utf-8").write(preamble)

# 2) per-video briefs + parsed transcripts
rows = []
for line in open(NEWVIDS):
    line = line.strip()
    if not line or "|" not in line: continue
    vid, title = [x.strip() for x in line.split("|", 1)]
    sl = slug(title)
    tpath = f"{BASE}/transcript_{sl}_{vid}.txt"
    words = 0
    vtts = sorted(glob.glob(f"{VTT_DIR}/{vid}*.vtt"))
    if vtts:
        text = parse_vtt(vtts[0]); open(tpath, "w").write(text); words = len(text.split())
    brief = f"""# VIDEO-RESEARCH BRIEF — {title}
**Video:** {title}
**URL:** https://youtu.be/{vid}
**Transcript (fetched + parsed, {words} words):** {tpath}
**Fleet-relevance pre-screen:** {tier(vid)}

> BEFORE DISPATCH: prepend `_DISPATCH_PREAMBLE.md` (the shared method).

## Task
Run the full video-research method (§1-§4 in the preamble) on this video, working from the parsed transcript above.
Focus §3 relevance on the six configured project buckets and the evidence in this video.
The exact buckets are: {" · ".join(PROJECTS)}.

## Dispatch
- Full-leg roster: EDIT ME: your cloud/local leg roster.
- Scoped audit: EDIT ME: your scoped-audit leg and remit.
- OUTPUT: `{BASE}/RESULT_{sl}_<backbone>.md` (first line: `Generated by: <backbone>`)
- Then reconcile legs -> `FINAL_{sl}_<date>.md`; gemma-audit; build the visual edition + hub card.
"""
    open(f"{OUT}/{sl}_{vid}.md", "w").write(brief)
    rows.append((tier(vid), vid, title, sl, words))

# 3) master queue (tiered)
order = {"HIGH": 0, "MED": 1, "LOW": 2}
rows.sort(key=lambda r: (order[r[0]], r[2].lower()))
q = ["# STAGING QUEUE — NEW playlist videos (no report yet)", "",
     f"{len(rows)} videos staged. Dispatch HIGH first"
     + (f"; **{PRIORITY_PIN} is the owner's priority**." if PRIORITY_PIN else "."),
     "Full-leg roster = EDIT ME: your cloud/local leg roster. Dispatch in waves sized for your fleet. "
     "Prepend `_DISPATCH_PREAMBLE.md`.", "",
     "| Tier | Video | Brief | Words |", "|---|---|---|---|"]
for t, vid, title, sl, words in rows:
    star = " ⭐" if vid == PRIORITY_PIN else ""
    q.append(f"| {t}{star} | [{title}](https://youtu.be/{vid}) | `{sl}_{vid}.md` | {words} |")
open(f"{OUT}/STAGING_QUEUE.md", "w").write("\n".join(q) + "\n")
print(f"staged {len(rows)} briefs + transcripts -> {OUT}")
print("HIGH:", sum(1 for r in rows if r[0] == "HIGH"), "| MED:", sum(1 for r in rows if r[0] == "MED"),
      "| LOW:", sum(1 for r in rows if r[0] == "LOW"))
miss = [r[1] for r in rows if r[4] == 0]
print("transcripts parsed:", sum(1 for r in rows if r[4] > 0), "| empty:", miss)
